#!/bin/bash
# BetzBotz One-Click Installer
# Usage: curl -fsSL https://raw.githubusercontent.com/betzbotz1/betzbotz-bot1/main/install.sh | bash -s -- "PRIVATE_KEY" "API_KEY" "SECRET"

set -e

POLYMARKET_PRIVATE_KEY="${1:-}"
POLYMARKET_API_KEY="${2:-}"
API_SECRET_KEY="${3:-$(openssl rand -hex 32)}"

echo "=============================================="
echo "  🤖 BetzBotz Installer"
echo "=============================================="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "❌ Please run as root (use sudo)"
  exit 1
fi

# Update system
echo "📦 Updating system packages..."
apt-get update -qq
apt-get upgrade -y -qq

# Install dependencies
echo "📦 Installing dependencies..."
apt-get install -y -qq python3 python3-pip python3-venv git curl ufw

# Setup firewall
echo "🔒 Configuring firewall..."
ufw allow 22/tcp   # SSH
ufw allow 8000/tcp # Bot API
ufw --force enable

# Create bot user if doesn't exist
echo "👤 Creating betzbotz user..."
id -u betzbotz &>/dev/null || useradd -m -s /bin/bash betzbotz

# Clone or update bot repository
echo "📥 Downloading BetzBotz..."
BOT_DIR="/home/betzbotz/bot"
if [ -d "$BOT_DIR" ]; then
  cd "$BOT_DIR"
  git pull origin main
else
  git clone https://github.com/betzbotz1/betzbotz-bot1.git "$BOT_DIR"
  cd "$BOT_DIR"
fi

# Set ownership
chown -R betzbotz:betzbotz /home/betzbotz

# Setup Python virtual environment
echo "🐍 Setting up Python environment..."
sudo -u betzbotz python3 -m venv "$BOT_DIR/venv"
sudo -u betzbotz "$BOT_DIR/venv/bin/pip" install --upgrade pip -q
sudo -u betzbotz "$BOT_DIR/venv/bin/pip" install -r "$BOT_DIR/requirements.txt" -q

# Create .env configuration
echo "⚙️ Creating configuration..."
cat > "$BOT_DIR/.env" << EOF
# BetzBotz Configuration
# Generated by installer on $(date)

# Polymarket Credentials
POLYMARKET_PRIVATE_KEY=${POLYMARKET_PRIVATE_KEY}
POLYMARKET_API_KEY=${POLYMARKET_API_KEY}

# Bot Settings
MAX_BET_PER_SIDE=0.50
MIN_MARKET_VOLUME=500
MAX_ENTRY_PRICE=0.05
MIN_HOURS_TO_EXPIRY=48
MAX_DAYS_TO_EXPIRY=90

# AI Settings (disabled by default)
OPENAI_API_KEY=
AI_MODE_ENABLED=false

# API Settings
API_PORT=8000
API_SECRET_KEY=${API_SECRET_KEY}
CORS_ORIGINS=https://betzbotz.app,http://localhost:3000

# Logging
LOG_LEVEL=INFO
EOF

chown betzbotz:betzbotz "$BOT_DIR/.env"
chmod 600 "$BOT_DIR/.env"

# Create systemd service
echo "🔧 Creating system service..."
cat > /etc/systemd/system/betzbotz.service << EOF
[Unit]
Description=BetzBotz Trading Bot
After=network.target

[Service]
Type=simple
User=betzbotz
WorkingDirectory=/home/betzbotz/bot
Environment=PATH=/home/betzbotz/bot/venv/bin:/usr/bin
ExecStart=/home/betzbotz/bot/venv/bin/python main.py --api
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

# Create logs directory
mkdir -p "$BOT_DIR/logs"
chown betzbotz:betzbotz "$BOT_DIR/logs"

# Enable and start service
echo "🚀 Starting BetzBotz..."
systemctl daemon-reload
systemctl enable betzbotz
systemctl restart betzbotz

# Wait for service to start
sleep 3

# Check if running
if systemctl is-active --quiet betzbotz; then
  PUBLIC_IP=$(curl -s ifconfig.me)
  echo ""
  echo "=============================================="
  echo "  ✅ BetzBotz Installed Successfully!"
  echo "=============================================="
  echo ""
  echo "  🌐 Bot API: http://${PUBLIC_IP}:8000"
  echo "  🔑 API Key: ${API_SECRET_KEY}"
  echo ""
  echo "  📊 View logs: journalctl -u betzbotz -f"
  echo "  🔄 Restart:   systemctl restart betzbotz"
  echo "  ⏹️  Stop:      systemctl stop betzbotz"
  echo ""
  echo "=============================================="
  
  # Output JSON for API parsing
  echo ""
  echo "BETZBOTZ_INSTALL_SUCCESS"
  echo "{\"success\":true,\"api_url\":\"http://${PUBLIC_IP}:8000\",\"api_key\":\"${API_SECRET_KEY}\"}"
else
  echo ""
  echo "❌ Installation failed. Check logs with: journalctl -u betzbotz -e"
  echo "BETZBOTZ_INSTALL_FAILED"
  exit 1
fi
